services:
  - type: web
    name: metagro-api
    runtime: node
    plan: free
    env: node
    buildCommand: npm install --prefix backend
    startCommand: npm start --prefix backend
    envVars:
      - key: MG_TOKEN
        sync: false
      - key: ADMIN_USER
        sync: false
      - key: ADMIN_PASS
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: POSTGRES_URL
        sync: false
      - key: NODE_ENV
        value: production