# Generated by Django 5.2.15 on 2026-06-23 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(db_index=True, max_length=255)),
                ('categoria', models.CharField(blank=True, db_index=True, max_length=255)),
                ('descripcion', models.TextField(blank=True, default='')),
                ('imagen_principal', models.ImageField(blank=True, null=True, upload_to='productos/')),
                ('precio', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('stock', models.IntegerField(blank=True, null=True)),
                ('destacado', models.BooleanField(db_index=True, default=False)),
                ('slug', models.SlugField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['categoria', 'id'],
                'indexes': [models.Index(fields=['categoria', 'destacado'], name='catalog_pro_categor_6e208b_idx')],
            },
        ),
    ]
